#!/bin/bash - 
### diplay-manager in systemd symlink is supported and tested on these distros : 
	# manjaro, mint 
# reset terminal
tput reset
if [[ $1 = @(-i|--install) ]]; then
	# section to install clidis as dm
	if [ ! -e $HOME/.clidis ] ;then 
		[ $(which curl) ] && curl https://raw.githubusercontent.com/virtualdemon/clidis/master/clidis -o ~/.clidis
		[ $(which wget) ] && wget https://raw.githubusercontent.com/virtualdemon/clidis/master/clidis -O ~/.clidis
	fi
	if [ $(systemctl is-enabled display-manager) ]; then
		echo "Disabling display manager service"
		file /etc/systemd/system/display-manager.service |  sed 's:.*/::' > $HOME/.cache/current_display_manager_which_disabled_for_clidis
		sudo systemctl disable display-manager.service
	else
		echo "I didn't find any display-manager service running on your system! maybe it's already disabled or there's a problem with it!"
	fi
	# enable clidis after login
	[ $(echo $SHELL | grep bash) ] && [[ ! $(grep "exec bash $HOME/.clidis"  ~/.bash_profile) ]] && echo "exec bash $HOME/.clidis" >> ~/.bash_profile || echo "clidis is already enabled in $HOME/.bash_profile !"
	[ $(echo $SHELL | grep zsh) ] && [[ ! $(grep "exec bash $HOME/.clidis"  ~/.zprofile) ]] && echo "exec bash $HOME/.clidis" >> ~/.zprofile || echo "clidis is already enabled in $HOME/.zprofile !"
	[ $(echo $SHELL | grep fish) ] && [[ ! $(grep "exec bash $HOME/.clidis"  ~/.config/fish/config.fish) ]] && echo "exec bash $HOME/.clidis" >> ~/.config/fish/config.fish || echo "clidis is already enabled in $HOME/.config/fish/config.fish !"
	echo "done! please reboot your system to see what happend!"
	exit
fi
if [[ $1 = @(-u|--uninstall|--remove) ]]; then
	# section to uninstall clidis
	if [ -e $HOME/.cache/current_display_manager_which_disabled_for_clidis ] ; then 
		if [ ! $(systemctl is-enabled display-manager) ] ; then
			displayManager=$(cat $HOME/.cache/current_display_manager_which_disabled_for_clidis)
			echo "Enabling $displayManager ! please confirm root access!"
			sudo systemctl enable $displayManager
		else
			echo "There's a problem! your display manager is enabled! please check it : systemctl status display-manager.service"
		fi
	else
		echo "I don't know your display manager service name! maybe your installed clidis manually so you can't remove it automatically... just give me your display manger name : "
		while true ; do
			read -p "Please type your installed display manager name (lightdm, ssdm, gdm,...) : " displayManager
			if [ $(which $displayManager) ] ; then
				sudo systemctl enable $displayManager
				break
			else
				echo "The $displayManger doesn't exist on your system. please try again."
				sleep 5
				clear
			fi
		done
	fi

	# disable clidis after login
	[ $(echo $SHELL | grep bash) ] && [[ $(grep "exec bash $HOME/.clidis"  ~/.bash_profile) ]] && sed -i.bak "/clidis/d" ~/.bash_profile || echo "clidis doesn't enabled in $HOME/.bash_profile !"
	[ $(echo $SHELL | grep zsh) ] && [[ $(grep "exec bash $HOME/.clidis"  ~/.zprofile) ]] && sed -i.bak "/clidis/d" ~/.zprofile || echo "clidis doesn't enabled in $HOME/.zprofile !"
	[ $(echo $SHELL | grep fish) ] && [[ $(grep "exec bash $HOME/.clidis"  ~/.config/fish/config.fish) ]] && sed -i.bak "/clidis/d" ~/.config/fish/config.fish || echo "clidis doesn't enabled in $HOME/.config/fish/config.fish !"

	echo "done! please reboot your system to see what happend!"
	exit
fi
